spring:
  redis:
    host: 39.101.74.139
    port: 6379
    password: Root_1234
    database: 0

#  datasource:
#    url: jdbc:mysql://39.101.74.139:3306/cloud-order
#    username: zmz
#    password: Root_1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
