spring:
  redis:
    host: 39.101.74.139
    port: 6379
    password: Root_1234
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
